spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/waystay
spring.datasource.username=root
spring.datasource.password=mainak2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

